<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>50fecf91-b1c5-4e53-81e0-1b5dda7159cc</groupId>
	<artifactId>cupa-salesforce-product-feed-papi-impl</artifactId>
	<version>1.0.5-SNAPSHOT</version>
	<packaging>mule-application</packaging>

	<name>cupa-salesforce-product-feed-papi</name>

	<parent>
		<groupId>org.cambridgeassessment</groupId>
		<artifactId>mule-parent-pom</artifactId>
		<version>1.1.1-RELEASE</version>
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<sonar.sources>src/</sonar.sources>
		<sonar.coverage.jacoco.xmlReportPaths>../target/site/munit/coverage/sonar.xml</sonar.coverage.jacoco.xmlReportPaths>
		<organizationId>${project.groupId}</organizationId>
		<api.name>cupa-salesforce-product-feed-papi</api.name>
		<api.version>1.0.7</api.version>
		<api.specification>resource::${organizationId}:${api.name}:${api.version}:raml:zip:api.raml</api.specification>
		<extract.dynamicPeriod>P1D</extract.dynamicPeriod>
	</properties>

	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.mule.tools.maven</groupId>
				<artifactId>mule-maven-plugin</artifactId>
				<extensions>true</extensions>
				<configuration>
					<cloudhub2Deployment>
						<secureProperties>
							<PROP03>${PROP01}</PROP03>
						</secureProperties>
						<properties>
							<extract.dynamicPeriod>${extract.dynamicPeriod}</extract.dynamicPeriod>
						</properties>
					</cloudhub2Deployment>
					<classifier>mule-application</classifier>
				</configuration>
				<version>4.3.0</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<compilerArgs>
						<args>-parameters</args>
					</compilerArgs>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.mulesoft.munit.tools</groupId>
				<artifactId>munit-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>test</id>
						<phase>test</phase>
						<goals>
							<goal>test</goal>
							<goal>coverage-report</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<coverage>
						<runCoverage>true</runCoverage>
						<formats>
							<format>html</format>
						</formats>
					</coverage>
				</configuration>
			</plugin>
		</plugins>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.sonarsource.scanner.maven</groupId>
					<artifactId>sonar-maven-plugin</artifactId>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

	<dependencies>
		<dependency>
			<groupId>${organizationId}</groupId>
			<artifactId>${api.name}</artifactId>
			<version>${api.version}</version>
			<classifier>raml</classifier>
			<type>zip</type>
		</dependency>
		<!-- <dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-runner</artifactId>
			<version>3.0.0</version>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-tools</artifactId>
			<version>3.1.0</version>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency>-->
		<!-- MUNIT -->
		<dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-runner</artifactId>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mule.weave</groupId>
			<artifactId>assertions</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mule.modules</groupId>
			<artifactId>mule-apikit-module</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-http-connector</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.modules</groupId>
			<artifactId>mule-secure-configuration-property-module</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-sockets-connector</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-file-connector</artifactId>
			<version>1.5.5</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-objectstore-connector</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>

		<!--  <dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-tools</artifactId>
			<version>3.0.0</version>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency>-->
		<!-- <dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-tools</artifactId>
			<version>3.0.0</version>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency> -->
		<dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-tools</artifactId>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.24.3</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>2.24.3</version>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>anypoint-exchange-v3</id>
			<name>Anypoint Exchange</name>
			<url>https://maven.anypoint.mulesoft.com/api/v3/maven</url>
			<layout>default</layout>
		</repository>
		<repository>
			<id>mulesoft-releases</id>
			<name>MuleSoft Releases Repository</name>
			<url>https://repository.mulesoft.org/releases/</url>
			<layout>default</layout>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>mulesoft-releases</id>
			<name>MuleSoft Releases Repository</name>
			<layout>default</layout>
			<url>https://repository.mulesoft.org/releases/</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>
	<distributionManagement>
		<repository>
			<id>MuleMavenFacadeAPIv3</id>
			<name>Corporate Repository</name>
			<url>https://maven.anypoint.mulesoft.com/api/v3/organizations/${project.groupId}/maven</url>
			<layout>default</layout>
		</repository>
		<snapshotRepository>
			<id>MuleMavenFacadeAPIv3</id>
			<name>Corporate Repository</name>
			<url>https://maven.anypoint.mulesoft.com/api/v3/organizations/${project.groupId}/maven</url>
			<layout>default</layout>
		</snapshotRepository>
	</distributionManagement>

</project>
